naruto/main/forms.py
# -*-coding:utf-8-*-

#这是表单文件

from flask_wtf import Form
from wtforms import StringField,SubmitField,TextAreaField,BooleanField,SelectField
from wtforms.validators import Required,Length,Email,Regexp
from ..models import Role,User
from flask_pagedown.fields import PageDownField

class PostForm(Form):
    body=PageDownField('写下你想说的',validators=[Required()])
    submit=SubmitField('发表文章')
#普通用户资料表单   
class EditProfileForm(Form):
    username=StringField('新昵称',validators=[Length(0,64),Regexp('^[^0-9].*$',0,'第一个字符不能是数字，那样太丑！')])
    name=StringField('真实姓名',validators=[Length(0,64)])
    location=StringField('坐标',validators=[Length(0,64)])
    about_me=TextAreaField('我的信息')
    submit=SubmitField('提交')
    
#管理员资料表单
class EditProfileAdminForm(Form):
    email=StringField('邮箱地址',validators=[Required(),Length(1,64),Email()])
    username=StringField('昵称',validators=[Required(),Length(1,64),Regexp('^[^0-9].*$',0,'第一个字符不能是数字，那样太丑！')])
    confirmed=BooleanField('确认')
    role=SelectField('角色',coerce=int)
    name=StringField('真实姓名',validators=[Length(0,64)])
    location=StringField('坐标',validators=[Length(0,64)])
    about_me=TextAreaField('我的信息')
    submit=SubmitField('提交')
    
    def __init__(self,user,*args,**kwargs):
        super(EditProfileAdminForm,self).__init__(*args,**kwargs)
        self.role.choices=[(role.id,role.name) for role in Role.query.order_by(Role.name).all()]#为上边selectfield做选项，id对应标识符，name标志对象
        self.user=user
    #检查邮箱和用户名是否发生变化，若发生就查看其余已存在数据库中的有没有重合    
    def validate_email(self,field):
        if field.data!=self.user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经注册.')
        
    def validate_username(self,field):
        if field.data!=self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已经注册.')
        
#评论提交表单
class CommentForm(Form):
    body=StringField('',validators=[Required()])
    submit=SubmitField('提交')


        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    

naruto/__init__.py
#-*-coding:utf-8-*-

#这是程序的构造文件，文件名为__init__

from flask import Flask,render_template
from flask_bootstrap import Bootstrap
from flask_mail import Mail
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy
from config import config
from flask_login import LoginManager
from flask_pagedown import PageDown


bootstrap=Bootstrap()
mail=Mail()
moment=Moment()
db=SQLAlchemy()
login_manager=LoginManager()
pagedown=PageDown()
login_manager.session_protection='strong'
#设置登录端点，因为前面注册认证蓝本时加了前缀
login_manager.login_view='auth.login'

def create_app(config_name): 
    app=Flask(__name__)
    app.config.from_object(config[config_name])
    config[config_name].init_app(app)
    
    #这些类的实例的创建都是一样？？？
    bootstrap.init_app(app)
    moment.init_app(app)
    mail.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)
    
    #注册路由主体蓝本，即访问蓝本后第一个页面 第一个是文件夹，第二个是蓝本实例
    from .main import main as main_blueprint
    #注册蓝本
    app.register_blueprint(main_blueprint)
    
    #认证蓝本
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')
    
    #api蓝本
    from .api_1_0 import api as api_1_0_blueprint
    app.register_blueprint(api_1_0_blueprint,url_prefix='/api/v1.0')
    
    return app
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    

naruto/api_1_0/__init__.py
#-*- coding:utf-8 -*-

#这是api 1.0版

from flask import Blueprint
api=Blueprint('api',__name__)
from . import authentication,posts,users,comments,errors

naruto/main/__init__.py
#-*-coding:utf-8-*-

#这是一个蓝本的构造文件

from flask import Blueprint

#创建蓝本实例，main是对象。括号内的第一个是蓝本名称
main=Blueprint('main',__name__)

from . import views,errors
from ..models import Permission

@main.app_context_processor
def inject_permissions():
    return dict(Permission=Permission)

naruto/main/views.py
#-*-coding:utf-8-*-

#这是蓝本的视图处理文件

import sys
default_encoding = 'utf-8'
if sys.getdefaultencoding() != default_encoding:
    reload(sys)
    sys.setdefaultencoding(default_encoding)

#扩展包
from datetime import datetime
from flask import render_template,session,redirect,url_for,flash,abort,request,make_response,current_app
from flask_login import login_required,current_user
from flask_sqlalchemy import get_debug_queries

#本地包
from . import main
from .forms import EditProfileForm,EditProfileAdminForm,PostForm,CommentForm
from .. import db
from ..models import User,Role,Permission,Post,Comment
from ..decorators import admin_required,permission_required

#创建蓝本路由
@main.route('/',methods=['GET','POST'])
def index():
    form=PostForm()
    if current_user.can(Permission.WRITE_ARTICLES) and form.validate_on_submit():
        post=Post(body=form.body.data,author=current_user._get_current_object())
        db.session.add(post)
        return redirect(url_for('.index'))
    page=request.args.get('page',1,type=int)
    show_followed=False
    if current_user.is_authenticated():
        show_followed=bool(request.cookies.get('show_followed',''))
    if show_followed:
        query=current_user.followed_posts
    else:
        query=Post.query    
    pagination=query.order_by(Post.timestamp.desc()).paginate(page,per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],error_out=False)
    posts=pagination.items
    return render_template('index.html',form=form,posts=posts,show_followed=show_followed,pagination=pagination)
  
        
#资料界面路由
@main.route('/user/<username>')
def user(username):
    user=User.query.filter_by(username=username).first_or_404()
    page=request.args.get('page',1,type=int)
    pagination=user.posts.order_by(Post.timestamp.desc()).paginate(page,per_page=current_app.config['FLASKY_POSTS_PER_PAGE'],error_out=False)
    posts=pagination.items
    return render_template('user.html',user=user,posts=posts,pagination=pagination)        
        
#资料编辑路由
@main.route('/edit_profile',methods=['GET','POST'])
@login_required
def edit_profile():
    form=EditProfileForm()
    if form.validate_on_submit():
        current_user.username=form.username.data
        current_user.name=form.name.data
        current_user.location=form.location.data
        current_user.about_me=form.about_me.data
        db.session.add(current_user)
        flash('你的资料已更新.')
        return redirect(url_for('.user',username=current_user.username))
    form.username.data=current_user.username
    form.name.data=current_user.name
    form.location.data=current_user.location
    form.about_me.data=current_user.about_me
    return render_template('edit_profile.html',form=form)        

#管理员编辑路由        
@main.route('/edit_profile/<int:id>',methods=['GET','POST'])
@login_required
@admin_required
def edit_profile_admin(id):
    user=User.query.get_or_404(id)
    form=EditProfileAdminForm(user=user)
    if form.validate_on_submit():
        user.email=form.email.data
        user.username=form.username.data
        user.confirmed=form.confirmed.data
        user.role=Role.query.get(form.role.data)
        user.name=form.name.data
        user.location=form.location.data
        user.about_me=form.about_me.data
        db.session.add(user)
        flash('你已经更新了该用户资料.')
        return redirect(url_for('.user',username=user.username))
    form.email.data=user.email
    form.username.data=user.username
    form.confirmed.data=user.confirmed
    form.role.data=user.role_id
    form.name.data=user.name
    form.location.data=user.location
    form.about_me.data=user.about_me
    return render_template('edit_profile.html',form=form)               
  

    
#编辑文章路由
@main.route('/edit/<int:id>',methods=['GET','POST'])
@login_required
def edit(id):
    post=Post.query.get_or_404(id)
    if current_user!=post.author and not current_user.can(Permission.ADMINISTER):
        abort(403)
    form=PostForm()
    if form.validate_on_submit():
        post.body=form.body.data
        db.session.add(post)
        flash('文章已更新.')
        return redirect(url_for('.index',id=post.id))
    form.body.data=post.body
    return render_template('edit_post.html',form=form)
    
#关注路由
@main.route('/follow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def follow(username):
    user=User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    if current_user.is_following(user):#防止用户直接使用url访问
        flash('你已经关注了该用户.')
        return redirect(url_for('.user',username=username))
    current_user.follow(user)
    flash('你正在关注 %s.'%username)
    return redirect(url_for('.user',username=username))

#取消关注路由
@main.route('/unfollow/<username>')
@login_required
@permission_required(Permission.FOLLOW)
def unfollow(username):
    user=User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    if current_user.is_following(user):#防止用户直接使用url访问
        flash('你还没有关注该用户.')
        current_user.unfollow(user)
        return redirect(url_for('.user',username=username))
    flash('你已经取消关注 %s.'%username)
    return redirect(url_for('.user',username=username))
       
#关注者视图
@main.route('/followers/<username>')
def followers(username):
    user=User.query.filter_by(username=username).first()
    if user is None:
        flash('Invalid user.')
        return redirect(url_for('.index'))
    page=request.args.get('page',1,type=int)
    pagination=user.follower.paginate(page,per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],error_out=False)
    follows=[{'user':item.follower,'timestamp':item.timestamp} for item in pagination.items]
    return render_template('followers.html',user=user,title="Followers of",endpoint='.followers',pagination=pagination,follows=follows)    

#关注的人的视图清单
@main.route('/followed_by/<username>')
def followed_by(username):
    user=User.query.filter_by(username=username).first()
    if user is None:
        flash('用户不存在.')
        return redirect(url_for('.index'))
    page=request.args.get('page',1,type=int)
    pagination=user.followed.paginate(page,per_page=current_app.config['FLASKY_FOLLOWERS_PER_PAGE'],error_out=False)
    follows=[{'user':item.followed,'timestamp':item.timestamp} for item in pagination.items]
    return render_template('followers.html',user=user,title="Followed by",endpoint='.followed_by',pagination=pagination,follows=follows)    

              
@main.route('/all')
@login_required
def show_all():
    resp=make_response(redirect(url_for('.index')))
    resp.set_cookie('show_followed','',max_age=30*24*60*60)
    return resp
    
@main.route('/followed')
@login_required
def show_followed():
    resp=make_response(redirect(url_for('.index')))
    resp.set_cookie('show_followed','1',max_age=30*24*60*60)
    return resp        
        
#文章评论路由
@main.route('/post/<int:id>',methods=['GET','POST'])
def post(id):
    post=Post.query.get_or_404(id)
    form=CommentForm()
    if form.validate_on_submit():
        comment=Comment(body=form.body.data,post=post,author=current_user._get_current_object())
        db.session.add(comment)
        flash('你的评论已发表.')
        return redirect(url_for('.post',id=post.id,page=-1))
    page=request.args.get('page',1,type=int)
    if page==-1:
        page=(post.comments.count()-1)/current_app.config['FLASKY_COMMENTS_PER_PAGE']+1
    pagination=post.comments.order_by(Comment.timestamp.asc()).paginate(page,per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],error_out=False)
    comments=pagination.items
    return render_template('post.html',posts=[post],form=form,comments=comments,pagination=pagination)        

#管理评论路由
@main.route('/moderate')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate():
    page=request.args.get('page',1,type=int)
    pagination=Comment.query.order_by(Comment.timestamp.desc()).paginate(page,per_page=current_app.config['FLASKY_COMMENTS_PER_PAGE'],error_out=False)
    comments=pagination.items
    return render_template('moderate.html',comments=comments,pagination=pagination,page=page)        
        
#评论路由权限
@main.route('/moderate/enable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_enable(id):
    comment=Comment.query.get_or_404(id)
    comment.disabled=False
    db.session.add(comment)
    return redirect(url_for('.moderate',page=request.args.get('page',1,type=int)))
    
@main.route('/moderate/disable/<int:id>')
@login_required
@permission_required(Permission.MODERATE_COMMENTS)
def moderate_disable(id):
    comment=Comment.query.get_or_404(id)
    comment.disabled=True
    db.session.add(comment)
    return redirect(url_for('.moderate',page=request.args.get('page',1,type=int)))           
        
#关闭服务器路由
@main.route('/shutdown')
def server_shutdown():
    if not current_app.testing:
        abort(404)
    shutdown =request.environ.get('werkzeug.server.shutdown')
    if not shutdown:
        abort(500)
    shutdown()
    return '关闭服务器...'       
        
#报告数据库查询
@main.after_app_request
def after_request(response):
    for query in get_debug_queries():
        if query.duration>=current_app.config['FLASK_SLOW_DB_QUERY_TIME']:
            current_app.logger.warning('查询过慢:%s\n名称:%s\n延迟:%s\n上下文:%s\n'%(query.statement,query.parameters,query.duration,query.context))
    return response        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

naruto/templates/_comments.html
<ul class="comments">
    {%for comment in comments%}
    <li class="comment">
        <div class="comment-thumnail">
            <a href="{{url_for('.user',username=comment.author.username)}}">
                <img class="img-rounded profile-thumnail" src="{{comment.author.gravatar(size=40)}}">
            </a>
        </div>
        <div class="comment-content">
            <div class="comment-date">{{moment(comment.timestamp).fromNow()}}</div>
            <div class="comment-author">
                <a href="{{url_for('.user',username=comment.author.username)}}">
                    {{comment.author.username}}</a></div>
            <div class="comment-body">
                {%if comment.disabled%}
                    <p><i>这条评论已经被管理员禁止.</i></p>
                {%endif%}
                {%if moderate or not comment.disabled%}
                    {%if comment.body_html%}
                        {{comment.body_html|safe}}
                    {%else%}
                        {{comment.body}}
                    {%endif%}
                {%endif%}
            </div>
            {%if moderate%}
                <br>
                {%if comment.disabled%}
                    <a class="btn btn-default btn-xs" href="{{url_for('.moderate_enable',id=comment.id,page=page)}}">禁止</a>
                {%else%}
                <a class="btn btn-danger btn-xs" href="{{url_for('.moderate_disable',id=comment.id,page=page)}}">开放</a>
                {%endif%}
            {%endif%}
        </div>
    </li>
    {%endfor%}
</ul>
            
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                

naruto/templates/_macros.html
{%macro pagination_widget(pagination,endpoint)%}
<ul class="pagination">
    <li{%if not pagination.has_prev%} class="disabled"{%endif%}>
        <a href="{%if pagination.has_prev%}{{url_for(endpoint,page=pagination.page-1,**kwargs)}}{%else%}#{%endif%}"> <!--瓒呴摼鎺ユ柇瑷€-->
        &laquo
        </a>
    </li>
    {%for p in pagination.iter_pages()%}
        {%if p%}
            {%if p==pagination.page%}
                <li class='active'>
                    <a href="{{url_for(endpoint,page=p,**kwargs)}}">{{p}}</a>
                </li>
            {%else%}
                <li>
                    <a href="{{url_for(endpoint,page=p,**kwargs)}}">{{p}}</a>
                </li>
            {%endif%}
        {%else%}
            <li class='disabled'><a href='#'>&hellip;</a></li>
        {%endif%}
    {%endfor%}
    <li {%if not pagination.has_next%} class="disabled"{%endif%}>
        <a href="{%if pagination.has_next%}{{url_for(endpoint,page=pagination.page+1,**kwargs)}}{%else%}#{%endif%}">
        &raquo
        </a>
    </li>
</ul>
{%endmacro%}
    

naruto/templates/_posts.html
<ul class='posts'>
    {%for post in posts%}
    <li class='post'>
        <div class="post-thumbnail">
            <a href="{{url_for('.user',username=post.author.username)}}">
            <img class="img-rounded profile-thumbnail" src="{{post.author.gravatar(size=40)}}">
            </a>
        </div>
        <div class="post-content">
            <div class="post-date">{{moment(post.timestamp).fromNow()}}</div>
                <div class="post-author">
                    <a href="{{url_for('.user',username=post.author.username)}}">
                        {{post.author.username}}
                    </a>
                </div>
                <div class="post-body">
                    {%if post.body_html%}
                        {{post.body_html|safe}}
                    {%else%}
                        {{post.body}}
                    {%endif%}
                </div>
                <div class="post-footer">
                    <a href="{{url_for('.post',id=post.id)}}">
                        <span class="label label-default">固定链接</span>
                    </a>
                    {%if current_user==post.author%}
                        <a href="{{url_for('.edit',id=post.id)}}">
                            <span class="label label-primary">编辑</span>
                        </a>
                    {%elif current_user.is_administrator()%}
                        <a href="{{url_for('.edit',id=post.id)}}">
                            <span class="label label-primary">编辑[管理员]</span>
                        </a>
                    {%endif%}
                    <a href="{{url_for('.post',id=post.id)}}#comments">
                    <span class="label label-primary">
                        {{post.comments.count()}}条评论
                    </span>
                    </a>
                </div>
        </div>
    </li>
    {%endfor%}
</ul>

naruto/templates/base.html
{%extends 'bootstrap/base.html'%}

{%block title%}芥子{%endblock%}

{%block head%}
{{super()}}
<link rel="shortcut icon" href="{{url_for('static',filename='Track.ico')}}" type="image/x-icon">
<link rel="icon" href="{{url_for('static',filename='Track.ico')}}" type="image/x-icon">
<link rel="stylesheet" href="{{url_for('static',filename='styles.css')}}" type="text/css">
{%endblock%}
{%block navbar%}
<div class="navbar navbar-inverse" role="navigation">
    <div class='container'>
        <div class="navbar-header">
            <button type='button' class="navbar-toggle"
            data-toggle='collapse' data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href='/'>享-极限</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                {%if current_user.is_authenticated()%}
                    <li><a href="{{url_for('main.user',username=current_user.username)}}">个人资料</a>
                {%endif%}
            </ul>       
            <ul class="nav navbar-nav navbar-right">
                {%if current_user.can(Permission.MODERATE_COMMENTS)%}
                        <li><a href="{{url_for('main.moderate')}}">管理评论</a></li>
                {%endif%}
                {%if current_user.is_authenticated()%}
                <li class='dropdown'>  
                    <a href='#' class="dropdown-toggle" data-toggle='dropdown'><img src="{{current_user.gravatar(size=20)}}">个人账户<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{url_for('auth.change_password')}}">修改密码</a></li>                        
                        <li><a href="{{url_for('auth.reset_email_address')}}">重置邮箱</a></li>
                        <li><a href="{{url_for('auth.logout')}}">退出账户</a></li>
                    </ul>   
                </li>
                {%else%}
                <li><a href="{{url_for('auth.login')}}">登录</a></li>
                {%endif%}
            </ul>                       
        </div>
    </div>
</div>
{%endblock%}

{%block content%}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}
    {%block page_content%}{%endblock%}
</div>
{%endblock%}

{%block scripts%}
{{super()}}
{{moment.include_moment()}}
{%endblock%}

















                

naruto/templates/edit_post.html
{%extends "base.html"%}
{%import "bootstrap/wtf.html" as wtf%}

{%block title%}须弥-编辑文章{%endblock%}
{%block page_content%}
<div class="page-header">
    <h1>编辑文章</h1>
</div>
<div>
    {{wtf.quick_form(form)}}
</div>
{%endblock%}

{%block scripts%}
    {{super()}}
    {{pagedown.include_pagedown()}}
{%endblock%}

naruto/templates/edit_profile.html
{%extends "base.html"%}
{%import "bootstrap/wtf.html" as wtf%}

{%block title%}Flasky - Edit Profile{%endblock%}

{%block page_content%}
<div class="page-header">
    <h1>编辑你的资料</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{%endblock%}

naruto/templates/followers.html
{%extends "base.html"%}
{%import "_macros.html" as macros%}

{%block title%}须弥 - {{title}}{{user.username}}{%endblock%}

{%block page_content%}
<div class="page-header">
    <h1>{{title}}{{user.username}}</h1>
</div>
<table class="table table-hover followers">
    <thread><tr><th>用户</th><th>since</th></tr></thread>
    {%for follow in follows%}
    {%if follow.user !=user%}
    <tr>
        <td>
            <a href="{{url_for('.user',username=follow.user.username)}}">
                <img class="img-rounded" src="{{follow.user.gravatar(size=32)}}">
                {{follow.user.username}}
            </a>
        </td>
        <td>{{moment(follow.timestamp).format('L')}}</td>
    </tr>
    {%endif%}
    {%endfor%}
</table>
<div class="pagination">
    {{macros.pagination_widget(pagination,endpoint,username=user.username)}}
</div>
{%endblock%}

naruto/templates/index.html
{%extends "base.html"%}
{%import "bootstrap/wtf.html" as wtf%}
{%import "_macros.html" as macros%}


{%block page_content%}
<div class="page-header">
    <h1>你好,{%if current_user.is_authenticated()%}{{current_user.username}}{%else%}有缘人{%endif%}!</h1>
</div>
<div>
    {% if current_user.can(Permission.WRITE_ARTICLES) %}
        {{wtf.quick_form(form)}}
    {% endif %}
</div>
<div class="post-tabs">
    <ul class="nav nav-tabs">
        <li {%if not show_followed%} class="active" {%endif%}>
            <a href="{{url_for('.show_all')}}">所有人</a></li>
        {%if current_user.is_authenticated()%}
        <li {%if show_followed%} class="active" {%endif%}>
            <a href="{{url_for('.show_followed')}}">关注的人</a></li>
        {%endif%}
    </ul>
    {%include '_posts.html'%}
</div>
{%if pagination%}
    <div class="pagination">
        {{macros.pagination_widget(pagination,'.index')}}
    </div>
{%endif%}
{%endblock%}
{%block scripts%}
    {{super()}}
    {{pagedown.include_pagedown()}}
{%endblock%}

naruto/templates/moderate.html
{%extends "base.html"%}
{%import "_macros.html" as macros%}

{%block title%}须弥 - 评论管理{%endblock%}

{%block page_content%}
    <div class="page-header">
        <h1>评论管理</h1>
    </div>
    {%set moderate=True%}
    {%include "_comments.html"%}
    {%if pagination%}
        <div class="pagination">
            {{macros.pagination_widget(pagination,'.moderate')}}
        </div>
    {%endif%}
{%endblock%}

naruto/templates/post.html
{%extends "base.html"%}
{%import "bootstrap/wtf.html" as wtf%}
{%import "_macros.html" as macros%}


{%block title%}须弥 -文章{%endblock%}

{%block page_content%}
    {%include '_posts.html'%}
    <h4 id="comment">评论</h4>
    {%if current_user.can(Permission.COMMENT)%}
        <div class="comment-form">
            {{wtf.quick_form(form)}}
        </div>
    {%endif%}
    {%include '_comments.html'%}
    {%if pagination%}
        <div class='pagination'>
            {{macros.pagination_widget(pagination,'.post',fragment='#comments',id=posts[0].id)}}
        </div>
    {%endif%}
{%endblock%}

naruto/templates/user.html
{%extends "base.html"%}
{%import "_macros.html" as macros%}

{%block title%}{{name}}-天地{%endblock%}
{%block page_content%}
<div class="page-header">
    <img class="img-rounded profile-thumbnail" src="{{user.gravatar(size=256)}}">
    <div class="profile-header">
    <h1>你好,{{user.username}}!</h1>
    {%if user.name or user.location%}
    <p>
        {%if user.name%}
        {{user.name}}
        {%endif%}
        {%if user.location%}
        来自<a href="http://ditu.amap.com/search?query={{user.location}}">{{user.location}}</a>
        {%endif%}
    </p>
    {%endif%}
    {%if current_user.is_administrator()%}
    <p><a href="mailto:{{user.email}}">{{user.email}}</a></p>
    {%endif%}
    {%if user.about_me%}<p>{{user.about_me}}</p>{%endif%}
    <p>
        注册时间:{{moment(user.member_since).format('L')}}.
        与上一次登录间隔: {{moment(user.last_seen).fromNow()}}.
    </p>
    <p>
        {%if current_user.can(Permission.FOLLOW) and user!=current_user%}
            {%if not current_user.is_following(user)%}
                <a href="{{url_for('.follow',username=user.username)}}" class="btn btn-primary">关注</a>
            {%else%}
                <a href="{{url_for('.unfollow',username=user.username)}}" class="btn btn-default">取消关注</a>
            {%endif%}
        {%endif%}
        <a href="{{url_for('.followers',username=user.username)}}">
            粉丝:<span class="badge">{{user.follower.count()-1}}</span>
        </a>
        <a href="{{url_for('.followed_by',username=user.username)}}">
            偶像:<span class="badge">{{user.followed.count()-1}}</span>
        </a>
        {%if current_user.is_authenticated() and user!=current_user and user.is_following(current_user)%}
            |<span class="label label-default">关注你的人</span>
        {%endif%}
                
    </p>
    <p>
    {%if current_user.is_administrator()%}
        <a class="btn btn-danger" href="{{ url_for('.edit_profile_admin',id=user.id)}}">
            编辑资料[管理员]
        </a>
    {%endif%}  
    {%if user==current_user and not current_user.is_administrator()%}
        <a class="btn btn-default" href="{{ url_for('.edit_profile') }}">
            编辑资料
        </a>
    {%endif%}     
    </p>
    <p>
    {%if current_user.is_administrator()%}
        <a class="btn btn-danger" href="{{ url_for('auth.delete_account_admin',id=user.id)}}">
            注销账户[管理员]
        </a>
    {%endif%}
    {%if current_user.is_authenticated() and not current_user.is_administrator()%}
        <a class="btn btn-default" href="{{url_for('auth.delete_account')}}">注销账户</a>
    {%endif%}    
    </p>   
    <h>{{user.username}}的文章</h3>
    {%include '_posts.html'%}
    {%if pagination%}
    <div class="pagination">
        {{macros.pagination_widget(pagination,'.user',username=username)}}
    </div>
    {%endif%}
    </div>
</div>
{%endblock%}